FProjectBundle\Entity\FosUserUser:
    type: entity
    table: fos_user_user
    uniqueConstraints:
        UNIQ_C560D76192FC23A8:
            columns:
                - username_canonical
        UNIQ_C560D761A0D96FBF:
            columns:
                - email_canonical
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        username:
            type: string
            nullable: false
            length: 255
            fixed: false
        usernameCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: username_canonical
        email:
            type: string
            nullable: false
            length: 255
            fixed: false
        emailCanonical:
            type: string
            nullable: false
            length: 255
            fixed: false
            column: email_canonical
        enabled:
            type: boolean
            nullable: false
        salt:
            type: string
            nullable: false
            length: 255
            fixed: false
        password:
            type: string
            nullable: false
            length: 255
            fixed: false
        lastLogin:
            type: datetime
            nullable: true
            column: last_login
        locked:
            type: boolean
            nullable: false
        expired:
            type: boolean
            nullable: false
        expiresAt:
            type: datetime
            nullable: true
            column: expires_at
        confirmationToken:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: confirmation_token
        passwordRequestedAt:
            type: datetime
            nullable: true
            column: password_requested_at
        roles:
            type: array
            nullable: false
            length: null
            fixed: false
        credentialsExpired:
            type: boolean
            nullable: false
            column: credentials_expired
        credentialsExpireAt:
            type: datetime
            nullable: true
            column: credentials_expire_at
        createdAt:
            type: datetime
            nullable: false
            column: created_at
        updatedAt:
            type: datetime
            nullable: false
            column: updated_at
        dateOfBirth:
            type: datetime
            nullable: true
            column: date_of_birth
        firstname:
            type: string
            nullable: true
            length: 64
            fixed: false
        lastname:
            type: string
            nullable: true
            length: 64
            fixed: false
        website:
            type: string
            nullable: true
            length: 64
            fixed: false
        biography:
            type: string
            nullable: true
            length: 1000
            fixed: false
        gender:
            type: string
            nullable: true
            length: 1
            fixed: false
        locale:
            type: string
            nullable: true
            length: 8
            fixed: false
        timezone:
            type: string
            nullable: true
            length: 64
            fixed: false
        phone:
            type: string
            nullable: true
            length: 64
            fixed: false
        facebookUid:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: facebook_uid
        facebookName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: facebook_name
        facebookData:
            type: json
            nullable: true
            column: facebook_data
        twitterUid:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: twitter_uid
        twitterName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: twitter_name
        twitterData:
            type: json
            nullable: true
            column: twitter_data
        gplusUid:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: gplus_uid
        gplusName:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: gplus_name
        gplusData:
            type: json
            nullable: true
            column: gplus_data
        token:
            type: string
            nullable: true
            length: 255
            fixed: false
        twoStepCode:
            type: string
            nullable: true
            length: 255
            fixed: false
            column: two_step_code
    manyToMany:
        group:
            targetEntity: FosUserGroup
            cascade: {  }
            mappedBy: null
            inversedBy: user
            joinTable:
                name: fos_user_user_group
                joinColumns:
                    -
                        name: user_id
                        referencedColumnName: id
                inverseJoinColumns:
                    -
                        name: group_id
                        referencedColumnName: id
            orderBy: null
    lifecycleCallbacks: {  }
