FProjectBundle\Entity\Joueur:
    repositoryClass: FProjectBundle\Entity\JoueurRepository
    type: entity
    table: joueur
    indexes:
        fk_club:
            columns:
                - id_club
        fk_poste:
            columns:
                - id_poste
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        prenom:
            type: string
            nullable: true
            length: 255
            fixed: false
        dateNaissance:
            type: date
            nullable: true
            column: date_naissance
        nationalite:
            type: string
            nullable: true
            length: 255
            fixed: false
        taille:
            type: integer
            nullable: true
            unsigned: false
            column: taille
        photo:
            type: string
            nullable: true
            length: 255
            fixed: false
        numMaillot:
            type: integer
            nullable: true
            unsigned: false
            column: num_maillot
    manyToOne:
        idClub:
            targetEntity: Club
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_club:
                    referencedColumnName: id
            orphanRemoval: false
        idPoste:
            targetEntity: Poste
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                id_poste:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
