FProjectBundle\Entity\Ligue:
    type: entity
    table: ligue
    repositoryClass: FProjectBundle\Entity\LigueRepository
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        nom:
            type: string
            nullable: false
            length: 255
            fixed: false
        logo:
            type: string
            nullable: true
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
