FProjectBundle\Entity\PhaseFinale:
    type: entity
    table: phase_finale
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        libelle:
            type: string
            nullable: false
            length: 255
            fixed: false
    lifecycleCallbacks: {  }
